# Site settings
encoding: utf-8
title: test
email: krong@techbreezesolutions.com
description: "test" # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://techbreezesolutions.com/" # the base hostname & protocol for your site

twitter_username: test1
github_username: test2

# Build settings
markdown: kramdown
